#!/bin/bash
# This script should be placed in /usr/local/bin
# Used at container startup

# Create users 
/usr/local/bin/createusers.sh

# We launch ssh daemon
echo "Starting sshd..."
/usr/bin/supervisord -c /etc/supervisor/supervisord.conf
